src/Entity/EmailLog.php
<?php

/*
 * This file is part of the fa bundle.
 *
 * @copyright Copyright (c) 2017, Fiare Oy
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Entity\Traits\TimestampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * EmailLog.
 *
 * @author Deep Panara
 *
 * @ORM\Entity(repositoryClass="App\Repository\EmailLogRepository")
 * @ORM\Table(
 *     name="email_log",
 * )
 * @ORM\HasLifecycleCallbacks
 */
class EmailLog
{
     use TimestampableTrait;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Id
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="template_id", type="string", nullable=true)
     */
    private $template_id;

    /**
     * @var string
     *
     * @ORM\Column(name="queue_id", type="integer")
     */
    private $queue_id;

    /**
     * @var string
     *
     * @ORM\Column(name="subject", type="string", nullable=true)
     */
    private $subject;

    /**
     * @var integer
     *
     * @ORM\Column(name="expected_sent_time", type="integer", length=10)
     */
    private $expected_sent_time;

    /**
     * @var integer
     *
     * @ORM\Column(name="real_sent_time", type="integer", length=10)
     */
    private $real_sent_at;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_sent", type="boolean")
     */
    private $is_sent;

    /**
     * @var array
     *
     * @ORM\Column(name="error", type="json", nullable=true)
     */
    private $error;

    /**
     * @var array
     *
     * @ORM\Column(name="mail_to", type="json")
     */
    private $mailTo;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var array
     *
     * @ORM\Column(name="cc", type="json", nullable=true)
     */
    private $cc;

    /**
     * @var array
     *
     * @ORM\Column(name="bcc", type="json", nullable=true)
     */
    private $bcc;

    /**
     * @var array
     *
     * @ORM\Column(name="mail_from", type="json", nullable=true)
     */
    private $mail_from;

    /**
     * @var array
     *
     * @ORM\Column(name="reply_to", type="json", nullable=true)
     */
    private $reply_to;

    /**
     * @var array
     *
     * @ORM\Column(name="custom_tags", type="json", nullable=true)
     */
    private $custom_tags;

    /**
     * @var array
     *
     * @ORM\Column(name="attachments", type="json", nullable=true)
     */
    private $attachments;

    /**
     * @var array
     *
     * @ORM\Column(name="headers", type="json", nullable=true)
     */
    private $headers;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return EmailLog
     */
    public function setId(int $id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return array
     */
    public function getMailTo()
    {
        return $this->mailTo;
    }

    /**
     * @param array $mailTo
     * @return EmailLog
     */
    public function setMailTo($mailTo)
    {
        $this->mailTo = $mailTo;

        return $this;
    }


    /**
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * @param string $subject
     * @return EmailLog
     */
    public function setSubject($subject)
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * @return array
     */
    public function getCc()
    {
        return $this->cc;
    }

    /**
     * @param array $cc
     * @return EmailLog
     */
    public function setCc($cc)
    {
        $this->cc = $cc;

        return $this;
    }

    /**
     * @return array
     */
    public function getBcc()
    {
        return $this->bcc;
    }

    /**
     * @param array $bcc
     * @return EmailLog
     */
    public function setBcc($bcc)
    {
        $this->bcc = $bcc;

        return $this;
    }

    /**
     * @return array
     */
    public function getMailFrom()
    {
        return $this->mail_from;
    }

    /**
     * @param array $from
     * @return EmailLog
     */
    public function setMailFrom($from)
    {
        $this->mail_from = $from;

        return $this;
    }

    /**
     * @return array
     */
    public function getReplyTo()
    {
        return $this->reply_to;
    }

    /**
     * @param array $reply_to
     * @return EmailLog
     */
    public function setReplyTo($reply_to)
    {
        $this->reply_to = $reply_to;

        return $this;
    }

    /**
     * @return array
     */
    public function getAttachments()
    {
        return $this->attachments;
    }

    /**
     * @param array $attachments
     * @return EmailLog
     */
    public function setAttachments($attachments)
    {
        $this->attachments = $attachments;

        return $this;
    }

    /**
     * @return array
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * @param array $headers
     * @return EmailLog
     */
    public function setHeaders($headers)
    {
        $this->headers = $headers;

        return $this;
    }

    /**
     * @return array
     */
    public function getCustomTags()
    {
        return $this->custom_tags;
    }

    /**
     * @param array $custom_tags
     * @return EmailLog
     */
    public function setCustomTags($custom_tags)
    {
        $this->custom_tags = $custom_tags;

        return $this;
    }

    /**
     * @return string
     */
    public function getTemplateId()
    {
        return $this->template_id;
    }

    /**
     * @param string $template_id
     * @return EmailLog
     */
    public function setTemplateId($template_id)
    {
        $this->template_id = $template_id;

        return $this;
    }

    /**
     * @return bool
     */
    public function isSent()
    {
        return $this->is_sent;
    }

    /**
     * @param bool $is_sent
     * @return EmailLog
     */
    public function setIsSent($is_sent)
    {
        $this->is_sent = $is_sent;

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param string $content
     * @return EmailLog
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return int
     */
    public function getExpectedSentTime()
    {
        return $this->expected_sent_time;
    }

    /**
     * @param int $expected_sent_time
     */
    public function setExpectedSentTime($expected_sent_time)
    {
        $this->expected_sent_time = $expected_sent_time;
    }

    /**
     * @return int
     */
    public function getRealSentAt()
    {
        return $this->real_sent_at;
    }

    /**
     * @param int $real_sent_at
     */
    public function setRealSentAt($real_sent_at)
    {
        $this->real_sent_at = $real_sent_at;
    }

    /**
     * @return array
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * @param array $error
     */
    public function setError($error)
    {
        $this->error = $error;
    }

    /**
     * @return string
     */
    public function getQueueId()
    {
        return $this->queue_id;
    }

    /**
     * @param string $queue_id
     */
    public function setQueueId($queue_id)
    {
        $this->queue_id = $queue_id;
    }



}

src/Form/EmailLogType.php
<?php

namespace App\Form;

use App\Entity\EmailLog;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmailLogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('template_id')
            ->add('queue_id')
            ->add('subject')
            ->add('expected_sent_time')
            ->add('real_sent_at')
            ->add('is_sent')
            ->add('error')
            ->add('mailTo')
            ->add('content')
            ->add('cc')
            ->add('bcc')
            ->add('mail_from')
            ->add('reply_to')
            ->add('custom_tags')
            ->add('attachments')
            ->add('headers')
            ->add('created_at')
            ->add('updated_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => EmailLog::class,
        ]);
    }
}

src/Controller/Web/EmailLogController.php
<?php

namespace App\Controller\Web;

use App\Entity\EmailLog;
use App\Form\EmailLogType;
use App\Repository\EmailLogRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/email/log")
 */
class EmailLogController extends AbstractController
{
    /**
     * @Route("/", name="email_log_index", methods={"GET"})
     */
    public function index(EmailLogRepository $emailLogRepository): Response
    {
        return $this->render('email_log/index.html.twig', [
            'email_logs' => $emailLogRepository->findBy([], ['expected_sent_time' => 'DESC'], 50),
        ]);
    }

    /**
     * @Route("/{id}", name="email_log_show", methods={"GET"})
     */
    public function show(EmailLog $emailLog): Response
    {
        return $this->render('email_log/show.html.twig', [
            'email_log' => $emailLog,
        ]);
    }

    /**
     * @Route("/{id}", name="email_log_delete", methods={"DELETE"})
     */
    public function delete(Request $request, EmailLog $emailLog): Response
    {
        if ($this->isCsrfTokenValid('delete'.$emailLog->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($emailLog);
            $entityManager->flush();
        }

        return $this->redirectToRoute('email_log_index');
    }
}

templates/email_log/_delete_form.html.twig
<form method="post" action="{{ path('email_log_delete', {'id': email_log.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ email_log.id) }}">
    <button class="btn">Delete</button>
</form>

templates/email_log/index.html.twig
{% extends 'base.html.twig' %}

{% block header_title %}
    <span class="font-weight-semibold">EmailLog </span> - index
{% endblock header_title %}

{% block body %}
    <!-- Single line -->
    <div class="card">
        <div class="card-header bg-transparent header-elements-inline">
            <h6 class="card-title">My Inbox (single line)</h6>
        </div>

        <!-- Action toolbar -->
        <div class="navbar navbar-light navbar-expand-lg shadow-0 py-lg-2">
            <div class="text-center d-lg-none w-100">
                <button type="button" class="navbar-toggler w-100" data-toggle="collapse" data-target="#inbox-toolbar-toggle-single">
                    <i class="icon-circle-down2"></i>
                </button>
            </div>

            <div class="navbar-collapse text-center text-lg-left flex-wrap collapse" id="inbox-toolbar-toggle-single">
                <div class="mt-3 mt-lg-0">
                    <div class="btn-group">
                        <button type="button" class="btn btn-light btn-icon btn-checkbox-all">
                            <input type="checkbox" class="form-input-styled" data-fouc>
                        </button>

                        <button type="button" class="btn btn-light btn-icon dropdown-toggle" data-toggle="dropdown"></button>
                        <div class="dropdown-menu">
                            <a href="#" class="dropdown-item">Select all</a>
                            <a href="#" class="dropdown-item">Clear selection</a>
                        </div>
                    </div>

                    <div class="btn-group ml-3 mr-lg-3">
                        <button type="button" class="btn btn-light"><i class="icon-bin"></i> <span class="d-none d-lg-inline-block ml-2">Delete</span></button>
                    </div>
                </div>

                <div class="navbar-text ml-lg-auto"><span class="font-weight-semibold">1-50</span> of <span class="font-weight-semibold">528</span></div>

                <div class="ml-lg-3 mb-3 mb-lg-0">
                    <div class="btn-group">
                        <button type="button" class="btn btn-light btn-icon disabled"><i class="icon-arrow-left12"></i></button>
                        <button type="button" class="btn btn-light btn-icon"><i class="icon-arrow-right13"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /action toolbar -->


        <!-- Table -->
        <div class="table-responsive">
            <table class="table table-inbox">
                <tbody data-link="row" class="rowlink">
                {% for email_log in email_logs %}
                    <tr class="unread">
                        <td class="table-inbox-checkbox rowlink-skip">
                            <input type="checkbox" class="form-input-styled" data-fouc>
                        </td>

                        <td class="table-inbox-name">
                            <a href="mail_read.html">
                                <div class="letter-icon-title text-default">{{ email_log.subject}}</div>
                            </a>
                        </td>
                        <td class="table-inbox-message">
                            <span class="badge badge-light badge-striped badge-striped-left mb-1">From</span>
                            <span class="text-muted font-weight-normal">{{ email_log.mailFrom|format_mail }}</span>
                            <br />
                            <span class="badge badge-light badge-striped badge-striped-left mb-1">To</span>
                            <span class="text-muted font-weight-normal">{{ email_log.mailTo|format_mail }}</span>
                        </td>
                        <td class="table-inbox-time">
                            {{ email_log.expectedSentTime|format_time }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /table -->

    </div>
    <!-- /single line -->
{% endblock %}

templates/email_log/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}EmailLog{% endblock %}

{% block body %}
    <h1>EmailLog</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ email_log.id }}</td>
            </tr>
            <tr>
                <th>Template_id</th>
                <td>{{ email_log.templateId }}</td>
            </tr>
            <tr>
                <th>Queue_id</th>
                <td>{{ email_log.queueId }}</td>
            </tr>
            <tr>
                <th>Subject</th>
                <td>{{ email_log.subject }}</td>
            </tr>
            <tr>
                <th>Expected_sent_time</th>
                <td>{{ email_log.expectedSentTime }}</td>
            </tr>
            <tr>
                <th>Real_sent_at</th>
                <td>{{ email_log.realSentAt }}</td>
            </tr>
            <tr>
                <th>Is_sent</th>
                <td>{{ email_log.isSent ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Error</th>
                <td>{{ email_log.error ? email_log.error|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>MailTo</th>
                <td>{{ email_log.mailTo ? email_log.mailTo|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ email_log.content }}</td>
            </tr>
            <tr>
                <th>Cc</th>
                <td>{{ email_log.cc ? email_log.cc|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Bcc</th>
                <td>{{ email_log.bcc ? email_log.bcc|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Mail_from</th>
                <td>{{ email_log.mailFrom ? email_log.mailFrom|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Reply_to</th>
                <td>{{ email_log.replyTo ? email_log.replyTo|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Custom_tags</th>
                <td>{{ email_log.customTags ? email_log.customTags|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Attachments</th>
                <td>{{ email_log.attachments ? email_log.attachments|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Headers</th>
                <td>{{ email_log.headers ? email_log.headers|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ email_log.createdAt }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ email_log.updatedAt }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('email_log_index') }}">back to list</a>

    <a href="{{ path('email_log_edit', {'id': email_log.id}) }}">edit</a>

    {{ include('email_log/_delete_form.html.twig') }}
{% endblock %}