src/Entity/EmailTemplate.php
<?php

/*
 * This file is part of the fa bundle.
 *
 * @copyright Copyright (c) 2017, Fiare Oy
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Entity\Traits\TimestampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * EmailTemplate.
 *
 * @author Deep Panara
 *
 * @ORM\Entity(repositoryClass="App\Repository\EmailTemplateRepository")
 * @ORM\Table(
 *     name="email_template",
 *     indexes={
 *      @ORM\Index(name="fa_email_template_name_index", columns={"name"}),
 *      @ORM\Index(name="fa_email_template_subject_index", columns={"subject"})
 *     }
 * )
 * @ORM\HasLifecycleCallbacks
 */
class EmailTemplate
{
    use TimestampableTrait;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="identifier", type="string", length=255, unique=true, nullable=true))
     */
    private $identifier;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\EmailGroup" )
     */
    private $email_group;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="subject", type="string", length=500)
     */
    private $subject;

    /**
     * @var string
     *
     * @ORM\Column(name="body_html", type="text")
     */
    private $body_html;

    /**
     * @var string
     *
     * @ORM\Column(name="body_text", type="text", nullable=true)
     */
    private $body_text;

    /**
     * @var array
     *
     * @ORM\Column(name="custom_tags", type="json", nullable=true)
     */
    private $custom_tags;

    /**
     * @var string
     *
     * @ORM\Column(name="sender_email", type="string", length=255)
     */
    private $sender_email;

    /**
     * @var string
     *
     * @ORM\Column(name="sender_name", type="string", length=50)
     */
    private $sender_name;

    /**
     * @var bool
     *
     * @ORM\Column(name="status", type="boolean", nullable=true)
     */
    private $status;

    /**
     * @var bool
     *
     * @ORM\Column(name="has_layout", type="boolean", nullable=true)
     */
    private $has_layout;

    /**
     * Construct.
     */
    public function __construct()
    {

    }

    /**
     * Set id.
     *
     * @param int $id
     *
     * @return EmailTemplate
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set identifier value.
     *
     * @ORM\PrePersist()
     */
    public function setIdentifierValue()
    {
        $this->identifier = strtoupper(bin2hex(random_bytes(8)));
    }

    /**
     * Get identifier.
     *
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Set name.
     *
     * @param string $name
     *
     * @return EmailTemplate
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set subject.
     *
     * @param string $subject
     *
     * @return EmailTemplate
     */
    public function setSubject($subject)
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * Get subject.
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Set body html.
     *
     * @param string $bodyHtml
     *
     * @return EmailTemplate
     */
    public function setBodyHtml($bodyHtml)
    {
        $this->body_html = $bodyHtml;

        return $this;
    }

    /**
     * Get body html.
     *
     * @return string
     */
    public function getBodyHtml()
    {
        return $this->body_html;
    }

    /**
     * Set body text.
     *
     * @param string $bodyText
     *
     * @return EmailTemplate
     */
    public function setBodyText($bodyText)
    {
        $this->body_text = $bodyText;

        return $this;
    }

    /**
     * Get body text.
     *
     * @return string
     */
    public function getBodyText()
    {
        return $this->body_text;
    }

    /**
     * Set sender email.
     *
     * @param string $senderEmail
     *
     * @return EmailTemplate
     */
    public function setSenderEmail($senderEmail)
    {
        $this->sender_email = $senderEmail;

        return $this;
    }

    /**
     * Get sender email.
     *
     * @return string
     */
    public function getSenderEmail()
    {
        return $this->sender_email;
    }

    /**
     * Set sender name.
     *
     * @param string $senderName
     *
     * @return EmailTemplate
     */
    public function setSenderName($senderName)
    {
        $this->sender_name = $senderName;

        return $this;
    }

    /**
     * Get sender name.
     *
     * @return string
     */
    public function getSenderName()
    {
        return $this->sender_name;
    }

    /**
     * Set status.
     *
     * @param bool $status
     *
     * @return EmailTemplate
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status.
     *
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Get has layout.
     *
     * @return string
     */
    public function getHasLayout()
    {
        return $this->has_layout;
    }

    /**
     * Sets has layout.
     *
     * @param string $value
     *
     * @return string
     */
    public function setHasLayout($value)
    {
        $this->has_layout = $value;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getEmailGroup() : ?EmailGroup
    {
        return $this->email_group;
    }

    /**
     * @param mixed $email_group
     */
    public function setEmailGroup(?EmailGroup $email_group)
    {
        $this->email_group = $email_group;
    }

    /**
     * @return array
     */
    public function getCustomTags()
    {
        return $this->custom_tags;
    }

    /**
     * @param array $custom_tags
     * @return EmailTemplate
     */
    public function setCustomTags($custom_tags)
    {
        $this->custom_tags = $custom_tags;

        return $this;
    }

}

src/Form/EmailTemplateType.php
<?php

namespace App\Form;

use App\Entity\EmailTemplate;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmailTemplateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
//            ->add('identifier')
            ->add('name')
            ->add('subject')
            ->add('body_html')
//            ->add('body_text')
            ->add('sender_email')
            ->add('sender_name')
            ->add('status')
            ->add('has_layout')
//            ->add('created_at')
//            ->add('updated_at')
//            ->add('email_group')
//            ->add('tags')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => EmailTemplate::class,
        ]);
    }
}

src/Controller/EmailTemplateController.php
<?php

namespace App\Controller;

use App\Entity\EmailTemplate;
use App\Form\EmailTemplateType;
use App\Manager\MailManager;
use App\Repository\EmailTemplateRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/email/template")
 */
class EmailTemplateController extends AbstractController
{
    /**
     * @Route("/", name="email_template_index", methods={"GET"})
     */
    public function index(EmailTemplateRepository $emailTemplateRepository, MailManager $mailManager): Response
    {
        return $this->render('email_template/index.html.twig', [
            'email_templates' => $emailTemplateRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="email_template_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $emailTemplate = new EmailTemplate();
        $form = $this->createForm(EmailTemplateType::class, $emailTemplate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($emailTemplate);
            $entityManager->flush();

            return $this->redirectToRoute('email_template_index');
        }

        return $this->render('email_template/new.html.twig', [
            'email_template' => $emailTemplate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="email_template_show", methods={"GET"})
     */
    public function show(EmailTemplate $emailTemplate): Response
    {
        return $this->render('email_template/show.html.twig', [
            'email_template' => $emailTemplate,
        ]);
    }

    /**
     * @Route("/{id}/preview", name="email_template_show_preview", methods={"GET"})
     */
    public function preview(EmailTemplate $emailTemplate): Response
    {
        return new Response($emailTemplate->getBodyHtml());
    }
    /**
     * @Route("/{id}/edit", name="email_template_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, EmailTemplate $emailTemplate): Response
    {
        $form = $this->createForm(EmailTemplateType::class, $emailTemplate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('email_template_index');
        }

        return $this->render('email_template/edit.html.twig', [
            'email_template' => $emailTemplate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="email_template_delete", methods={"DELETE"})
     */
    public function delete(Request $request, EmailTemplate $emailTemplate): Response
    {
        if ($this->isCsrfTokenValid('delete'.$emailTemplate->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($emailTemplate);
            $entityManager->flush();
        }

        return $this->redirectToRoute('email_template_index');
    }
}

src/Controller/Web/EmailTemplateController.php
<?php

namespace App\Controller\Web;

use App\Entity\EmailTemplate;
use App\Form\EmailTemplateType;
use App\Manager\MailManager;
use App\Repository\EmailLogRepository;
use App\Repository\EmailTemplateRepository;
use ReflectionClass;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/email/template")
 */
class EmailTemplateController extends AbstractController
{
    /**
     * @Route("/", name="email_template_index", methods={"GET"})
     */
    public function index(EmailTemplateRepository $emailTemplateRepository, MailManager $mailManager): Response
    {
        return $this->render('email_template/index.html.twig', [
            'email_templates' => $emailTemplateRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="email_template_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $emailTemplate = new EmailTemplate();
        $form = $this->createForm(EmailTemplateType::class, $emailTemplate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($emailTemplate);
            $entityManager->flush();

            return $this->redirectToRoute('email_template_index');
        }

        return $this->render('email_template/new.html.twig', [
            'email_template' => $emailTemplate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="email_template_show", methods={"GET"})
     */
    public function show(EmailTemplate $emailTemplate, EmailLogRepository $emailLogRepository): Response
    {
        $emailLog = $emailLogRepository->findBy(['template_id' => $emailTemplate->getIdentifier()], ['id' => 'DESC']);

        return $this->render('email_template/show.html.twig', [
            'email_template' => $emailTemplate,
            'email_log' => $emailLog
        ]);
    }

    /**
     * @Route("/{id}/preview", name="email_template_show_preview", methods={"GET"})
     */
    public function preview(EmailTemplate $emailTemplate): Response
    {
        return new Response($emailTemplate->getBodyHtml());
    }
    /**
     * @Route("/{id}/edit", name="email_template_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, EmailTemplate $emailTemplate): Response
    {
        $form = $this->createForm(EmailTemplateType::class, $emailTemplate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('email_template_index');
        }

        return $this->render('email_template/edit.html.twig', [
            'email_template' => $emailTemplate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="email_template_delete", methods={"DELETE"})
     */
    public function delete(Request $request, EmailTemplate $emailTemplate): Response
    {
        if ($this->isCsrfTokenValid('delete'.$emailTemplate->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($emailTemplate);
            $entityManager->flush();
        }

        return $this->redirectToRoute('email_template_index');
    }
}

templates/email_template/_delete_form.html.twig
<form id="delete_form" method="post" action="{{ path('email_template_delete', {'id': email_template.id}) }}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ email_template.id) }}">
    <button class="btn btn-outline-danger btn-sm m-1 btn-block"><i class="icon-bin"></i><span class="d-none d-lg-inline-block ml-2">Delete</span></button>
</form>

templates/email_template/edit.html.twig
{% extends 'base.html.twig' %}

{% block header_title %}
    <a class="btn-large" href="{{ path('email_template_show', {'id': email_template.id}) }}"><i class="icon-arrow-left52 mr-2"></i></a>
    Edit EmailTemplate #{{ email_template.id }}
{% endblock %}

{% block javascript %}
    <script src="{{ asset('global_assets/js/plugins/editors/ckeditor/ckeditor.js') }}"></script>
{% endblock %}

{% block body %}
    {{ include('email_template/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/email_template/index.html.twig
{% extends 'base.html.twig' %}

{% block header_title %}
    <span class="font-weight-semibold">EmailTemplate </span> - index
{% endblock header_title %}

{% block header_elements %}
    <a href="{{ path('email_template_new') }}" class="btn btn-primary" type="button"><i class="icon-plus3 mr-2"></i> Create new</a>
{% endblock header_elements %}

{% block body %}
<div class="card">
    <div class="card-body">
        <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="bg-slate">
                <th class="text-center">Id</th>
                <th class="text-center">Name</th>
                <th class="text-center">Subject</th>
                <th class="text-center">Sender Email</th>
                <th class="text-center">Sender Name</th>
                <th class="text-center">Status</th>
                <th class="text-center">Campaign</th>
                <th class="text-center">Updated At</th>
                <th class="text-center">Has Layout</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for email_template in email_templates %}

                <tr class="bg-light">
                    <td class="text-center">{{ email_template.id }}</td>
                    <td>{{ email_template.name }}</td>
                    <td>{{ email_template.subject }}</td>
                    <td class="text-center">{{ email_template.senderEmail }}</td>
                    <td class="text-center">{{ email_template.senderName }}</td>
                    <td class="text-center">{{ email_template.status ? '<span class="badge badge-primary">Active</span>' : '<span class="badge badge-secondary">Inactive</span>' }}</td>
                    <td class="text-center">{{ email_template.emailGroup.name }}</td>
                    <td class="text-center">{{ email_template.updatedAt|date('d-m-Y') }}</td>
                    <td class="text-center">{{ email_template.hasLayout ? 'Yes' : 'No' }}</td>
                    <td class="text-center">
                        <div class="list-icons">
                            <div class="dropdown">
                                <a href="javascript:void(0)" class="list-icons-item" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="{{ path('email_template_show', {'id': email_template.id}) }}" class="dropdown-item"><i class="icon-eye2"></i> Show</a>
                                    <a href="{{ path('email_template_edit', {'id': email_template.id}) }}" class="dropdown-item"><i class="icon-pencil"></i> Edit</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="14">no records found</td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
    </div>
</div>
{% endblock %}

templates/email_template/new.html.twig
{% extends 'base.html.twig' %}

{% block header_title %}
    <a class="btn-large" href="{{ path('email_template_index') }}"><i class="icon-arrow-left52 mr-2"></i></a>
    Edit EmailTemplate #{{ email_template.id }}
{% endblock %}

{% block javascript %}
<script src="{{ asset('global_assets/js/plugins/editors/ckeditor/ckeditor.js') }}"></script>
{% endblock %}

{% block body %}
    {{ include('email_template/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/email_template/show.html.twig
{% extends 'base.html.twig' %}

{% block header_title %}
    <a class="btn-large" href="{{ path('email_template_index') }}"><i class="icon-arrow-left52 mr-2"></i></a>
    Preview Email Template #{{ email_template.id }}
{% endblock %}

{% block body %}
<div class="card">
    <div class="card-body">
        <div class="d-md-flex">
            <ul class="nav nav-tabs nav-tabs-vertical flex-column mr-md-3 wmin-md-200 mb-md-0 border-bottom-0">
                <li class="nav-item"><a href="#vertical-left-statistics" class="nav-link active" data-toggle="tab"><i class="icon-graph mr-2"></i> Statistics</a></li>
                <li class="nav-item"><a href="#vertical-left-fields" class="nav-link" data-toggle="tab"><i class="icon-menu7 mr-2"></i> Fields</a></li>
                <li class="nav-item"><a href="#vertical-left-template" class="nav-link" data-toggle="tab"><i class="icon-html52 mr-2"></i> Email Template</a></li>
                <li class="nav-item"><a href="#vertical-left-tags" class="nav-link" data-toggle="tab"><i class="icon-code mr-2"></i> Tags</a></li>
                <li class="mt-0 mb-2">
                    <hr class="m-0">
                </li>
                <li class="list-inline-item mr-2 ml-0">
                    <a class="btn btn-outline-primary btn-sm m-1 btn-block" href="{{ path('email_template_edit', {'id': email_template.id}) }}"><i class="icon-pencil"></i><span class="d-none d-lg-inline-block ml-2">edit</span></a>
                </li>
                <li class="list-inline-item mr-2 ml-0">
                    <a class="btn btn-outline-primary btn-sm m-1 btn-block" href="#"><i class="icon-paperplane"></i><span class="d-none d-lg-inline-block ml-2">Send sample</span></a>
                </li>
                <li class="list-inline-item mr-2 ml-0">
                    <a class="btn btn-outline-primary btn-sm m-1 btn-block" href="#"><i class="icon-file-pdf"></i><span class="d-none d-lg-inline-block ml-2">export</span></a>
                </li>
                <li class="list-inline-item mr-2 ml-0">
                    {{- include('email_template/_delete_form.html.twig') -}}
                </li>
            </ul>

            <div class="tab-content" style="width: 100%">
                <div class="tab-pane fade active show" id="vertical-left-statistics">
                    <div class="row">
                        <div class="col-sm-6 col-xl-3">
                            <div class="card card-body">
                                <div class="media">
                                    <div class="mr-3 align-self-center">
                                        <i class="icon-pointer icon-3x text-success-400"></i>
                                    </div>

                                    <div class="media-body text-right">
                                        <h3 class="font-weight-semibold mb-0">652,549</h3>
                                        <span class="text-uppercase font-size-sm text-muted">total clicks</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6 col-xl-3">
                            <div class="card card-body">
                                <div class="media">
                                    <div class="mr-3 align-self-center">
                                        <i class="icon-enter6 icon-3x text-indigo-400"></i>
                                    </div>

                                    <div class="media-body text-right">
                                        <h3 class="font-weight-semibold mb-0">245,382</h3>
                                        <span class="text-uppercase font-size-sm text-muted">total visits</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6 col-xl-3">
                            <div class="card card-body">
                                <div class="media">
                                    <div class="media-body">
                                        <h3 class="font-weight-semibold mb-0">54,390</h3>
                                        <span class="text-uppercase font-size-sm text-muted">total comments</span>
                                    </div>

                                    <div class="ml-3 align-self-center">
                                        <i class="icon-bubbles4 icon-3x text-blue-400"></i>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6 col-xl-3">
                            <div class="card card-body">
                                <div class="media">
                                    <div class="media-body">
                                        <h3 class="font-weight-semibold mb-0">389,438</h3>
                                        <span class="text-uppercase font-size-sm text-muted">total orders</span>
                                    </div>

                                    <div class="ml-3 align-self-center">
                                        <i class="icon-bag icon-3x text-danger-400"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="tab-pane fade" id="vertical-left-fields">
                    <!-- Mail details -->
                    <div class="card-body border-top">
                        <div class="media flex-column flex-md-row">
                            <a href="#" class="d-none d-md-block mr-md-3 mb-3 mb-md-0">
                                <span class="btn bg-slate btn-icon btn-lg rounded-round">
                                    <span class="letter-icon ">{{ email_template.senderName|slice(0, 1)|lower }}</span>
                                </span>
                            </a>

                            <div class="media-body">
                                <h6 class="mb-0">{{ email_template.subject }}</h6>
                                <div class="letter-icon-title font-weight-semibold"><span class="text-muted small">From: </span>{{ email_template.senderName }} <a href="#">&lt;{{ email_template.senderEmail }}t&gt;</a></div>
                            </div>
                        </div>
                    </div>
                    <!-- /mail details -->

                    <!-- Mail details -->
                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                            <tr>
                                <td class="align-top py-0" style="width: 15%">
                                    <div class="py-2 mr-sm-3">Unice Identifier For Send:</div>
                                </td>
                                <td class="align-top py-0">
                                    <div class="d-sm-flex flex-sm-wrap py-2 px-0 border-0 rounded-0">
                                        {{ email_template.identifier }}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="align-top py-0" style="width: 15%">
                                    <div class="py-2 mr-sm-3">Name:</div>
                                </td>
                                <td class="align-top py-0">
                                    <div class="d-sm-flex flex-sm-wrap py-2 px-0 border-0 rounded-0">
                                        {{ email_template.name }}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="align-top py-0" style="width: 15%">
                                    <div class="py-2 mr-sm-3">Camapin:</div>
                                </td>
                                <td class="align-top py-0">
                                    <div class="d-sm-flex flex-sm-wrap py-2 px-0 border-0 rounded-0">
                                        {{ email_template.emailGroup.name }}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="align-top py-0" style="width: 15%">
                                    <div class="py-2 mr-sm-3">Status:</div>
                                </td>
                                <td class="align-top py-0">
                                    <div class="d-sm-flex flex-sm-wrap py-2 px-0 border-0 rounded-0">
                                        {{ email_template.status ? '<span class="badge badge-primary">Active</span>' : '<span class="badge badge-secondary">Inactive</span>' }}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="align-top py-0" style="width: 15%">
                                    <div class="py-2 mr-sm-3">Last Modified:</div>
                                </td>
                                <td class="align-top py-0">
                                    <div class="d-sm-flex flex-sm-wrap py-2 px-0 border-0 rounded-0">
                                        {{ email_template.updatedAt|date('d M h:m a') }}
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <!-- /mail details -->
                </div>

                <div class="tab-pane fade" id="vertical-left-template">
                    <iframe id='iframe2' allowfullscreen src="{{ path('email_template_show_preview', {'id': email_template.id }) }}" frameborder="0" style="overflow: hidden; height: 1500px;width: 100%;"></iframe>
                </div>

                <div class="tab-pane fade" id="vertical-left-tags">
{#                    <div class="row">#}
{#                        {% for tag in email_template.tags %}#}
{#                        <div class="col-md-3">#}
{#                            <div class="card">#}
{#                                <div class="card-header bg-light d-flex justify-content-between">#}
{#                                    <span class="font-size-sm text-uppercase font-weight-semibold">{{ tag.code }}</span>#}
{#                                </div>#}
{#                                <div class="card-body">#}
{#                                    {% if tag.decreption is not null %}#}
{#                                        {{ tag.decreption }}#}
{#                                    {% else %}#}
{#                                        <p class="text-muted">Decreption Not Avalable.</p>#}
{#                                    {% endif %}#}
{#                                </div>#}
{#                                <div class="card-footer bg-light d-flex justify-content-between">#}
{#                                    <ul class="list-inline mb-0">#}
{#                                        <li class="list-inline-item"><a class="text-warning" href="#">Remove From This Email </a></li>#}
{#                                    </ul>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                        {% endfor %}#}
{#                    </div>#}
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}